app/src/Entity/Club.php
<?php

namespace App\Entity;

use App\Entity\Traits\Active;
use App\Entity\Traits\Timestamps;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClubRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Club // extends JsonSerializableNormalizer
{
    use Active;
    use Timestamps;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $budget;

    /**
     * @ORM\Column(type="float")
     */
    private $budget_rest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="date")
     */
    private $foundation_year;

    /**
     * @ORM\OneToMany(targetEntity=Player::class, mappedBy="club")
     */
    private $players;

    /**
     * @ORM\OneToMany(targetEntity=Manager::class, mappedBy="club")
     */
    private $managers;

    public function __construct()
    {
        $this->players = new ArrayCollection();
        $this->managers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBudget(): ?float
    {
        return $this->budget;
    }

    public function setBudget(float $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getBudgetRest(): ?float
    {
        return $this->budget_rest;
    }

    public function setBudgetRest(float $budget_rest): self
    {
        $this->budget_rest = $budget_rest;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getFoundationYear(): ?\DateTimeInterface
    {
        return $this->foundation_year;
    }

    public function setFoundationYear(\DateTimeInterface $foundation_year): self
    {
        $this->foundation_year = $foundation_year;

        return $this;
    }

    /**
     * @return Collection|Player[]
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setClub($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getClub() === $this) {
                $player->setClub(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Manager[]
     */
    public function getManagers(): Collection
    {
        return $this->managers;
    }

    public function addManager(Manager $manager): self
    {
        if (!$this->managers->contains($manager)) {
            $this->managers[] = $manager;
            $manager->setClub($this);
        }

        return $this;
    }

    public function removeManager(Manager $manager): self
    {
        if ($this->managers->removeElement($manager)) {
            // set the owning side to null (unless already changed)
            if ($manager->getClub() === $this) {
                $manager->setClub(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

app/src/Form/ClubType.php
<?php

namespace App\Form;

use App\Entity\Club;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClubType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('budget')
            ->add('city')
            ->add('foundation_year')
            ->add('active')
            ->add('createdAt')
            ->add('updatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Club::class,
        ]);
    }
}

app/src/Controller/API_10/ClubController.php
<?php

namespace App\Controller\API_10;

use App\Helper\API10;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\ClubRepository;
use App\Entity\Club;
use App\Exception\BudgetException;
use App\Helper\ClubHelper;

#[Route('/API/1.0/club')]
class ClubController extends API10
{
    public function __construct (
        private EntityManagerInterface $entityManager, 
        private ManagerRegistry        $managerRegistry,
    )
    {
        // Powered by PHP 8.1 "in initializers" new feature. It makes
        // inneccesary to create and initilize the $this->repository variable

        $this->class      = Club::class;
        $this->repository = new ClubRepository ( $managerRegistry );
        $this->em         = $entityManager;
        $this->mr         = $managerRegistry;

        $this->serializer = function ( $collection )
        {
            $return = [ ];

            foreach ( $collection as $value )
            {
                $id = $value->getId ( );
                $return [ $id ] =
                [
                    'id'              => $id,
                    'name'            => $value->getName(),
                    'budget'          => $value->getBudget(),
                    'city'            => $value->getCity(),
                    'foundation_year' => $value->getFoundationYear(),
                    'active'          => $value->getActive(),
                    'created_at'      => $value->getCreatedAt(),
                    'update_at'       => $value->getUpdatedAt(),
                ];
            }

            return $return;
        };
        

        $this->persistObject = function ( $object, $content )
        {
            $decoded = json_decode ( $content );
    
            $object->setName           ( $decoded->name   ?? '' );
            $object->setBudget         ( $decoded->budget ?? '' );
            $object->setCity           ( $decoded->city   ?? '' );
            $object->setActive         ( $decoded->active ?? '0' );
            $object->setFoundationYear ( new \Datetime ( $decoded->foundation_year->date ?? NULL ) );
            
            $this->entityManager->persist (  $object );
            $this->entityManager->flush();
        };
    }


    #[Route("/", name: "API_10_club_index", methods: ["GET"])]
    public function index ( Request $request ): JsonResponse
    {
        return parent::index ( $request );
    }
    
    
    #[Route("/", name: "API_10_club_new", methods: ["POST"])]
    public function new ( Request $request ): JsonResponse
    {
        return parent::new ( $request );
    }


    #[Route("/{id}", name: "API_10_club_show", methods: ["GET"])]
    public function show ( Request $request ): JsonResponse
    {
        return parent::show ( $request );
    }


    #[Route("/{id}", name: "API_10_club_replace", methods: ["PUT"])]
    public function replace ( Request $request ): JsonResponse
    {
        return parent::replace ( $request );
    }


    #[Route("/{id}", name: "API_10_club_delete", methods: ["DELETE"])]
    public function delete ( Request $request ): JsonResponse
    {
        return parent::delete ( $request );
    }
    

    #[Route("/{id}", name: "API_10_club_update", methods: ["PATCH"])]
    public function update ( Request $request ): JsonResponse
    {
        try 
        {
            [ $presupuesto, $totalSalarios ] = ClubHelper::calculoPresupuestoYSalarios ( $request, $this->managerRegistry );

            if ( $presupuesto < $totalSalarios )
            {
                throw new BudgetException ( 'Invalid budget' );
            }
        }
        catch ( BudgetException $e )
        {
            return $this->createSerializedJSONResponse ( [ ], $e->getMessage() );    
        }

        return parent::update ( $request );
    }
}

app/src/Controller/CRUD/ClubController.php
<?php

namespace App\Controller\CRUD;

use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/CRUD/club')]
class ClubController extends AbstractController
{
    #[Route('/', name: 'club_index', methods: ['GET'])]
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('club/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'club_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $club = new Club();
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($club);
            $entityManager->flush();

            return $this->redirectToRoute('club_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('club/new.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'club_show', methods: ['GET'])]
    public function show(Club $club): Response
    {
        return $this->render('club/show.html.twig', [
            'club' => $club,
        ]);
    }

    #[Route('/{id}/edit', name: 'club_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('club_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('club/edit.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'club_delete', methods: ['POST'])]
    public function delete(Request $request, Club $club, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$club->getId(), $request->request->get('_token'))) {
            $entityManager->remove($club);
            $entityManager->flush();
        }

        return $this->redirectToRoute('club_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/club/_delete_form.html.twig
<form method="post" action="{{ path('club_delete', {'id': club.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/club/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/club/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Club{% endblock %}

{% block body %}
    <h1>Edit Club</h1>

    {{ include('club/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('club_index') }}">back to list</a>

    {{ include('club/_delete_form.html.twig') }}
{% endblock %}

app/templates/club/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club index{% endblock %}

{% block body %}
    <h1>Club index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Budget</th>
                <th>City</th>
                <th>Foundation_year</th>
                <th>Active</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for club in clubs %}
            <tr>
                <td>{{ club.id }}</td>
                <td>{{ club.name }}</td>
                <td>{{ club.budget }}</td>
                <td>{{ club.city }}</td>
                <td>{{ club.foundationYear ? club.foundationYear|date('Y-m-d') : '' }}</td>
                <td>{{ club.active }}</td>
                <td>{{ club.createdAt ? club.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ club.updatedAt ? club.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('club_show', {'id': club.id}) }}">show</a>
                    <a href="{{ path('club_edit', {'id': club.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('club_new') }}">Create new</a>
{% endblock %}

app/templates/club/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Club{% endblock %}

{% block body %}
    <h1>Create new Club</h1>

    {{ include('club/_form.html.twig') }}

    <a href="{{ path('club_index') }}">back to list</a>
{% endblock %}

app/templates/club/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
    <h1>Club</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ club.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ club.name }}</td>
            </tr>
            <tr>
                <th>Budget</th>
                <td>{{ club.budget }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ club.city }}</td>
            </tr>
            <tr>
                <th>Foundation_year</th>
                <td>{{ club.foundationYear ? club.foundationYear|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ club.active }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ club.createdAt ? club.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ club.updatedAt ? club.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('club_index') }}">back to list</a>
    |
    <a href="{{ path('club_edit', {'id': club.id}) }}">edit</a>

    {{ include('club/_delete_form.html.twig') }}
{% endblock %}