app/src/Entity/Player.php
<?php

namespace App\Entity;

use App\Entity\Traits\Active;
use App\Entity\Traits\Timestamps;
use Doctrine\ORM\Mapping as ORM;
use App\Exception\SalaryException;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PostPersist;
use Doctrine\ORM\Mapping\PostUpdate;
use Doctrine\ORM\Mapping\PrePersist;
use App\Helper\MessengerHelper;


/**
 * @ORM\Entity(repositoryClass=PlayerRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Player
{
    use Active;
    use Timestamps;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Club::class, inversedBy="players")
     */
    private $club;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $salary;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dorsal;

    /**
     * @ORM\Column(type="date")
     */
    private $birth_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClub(): ?Club
    {
        return $this->club;
    }

    public function setClub(?Club $club): self
    {
        $this->club = $club;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSalary(): ?float
    {
        return $this->salary;
    }

    public function setSalary(float $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getDorsal(): ?int
    {
        return $this->dorsal;
    }

    public function setDorsal(?int $dorsal): self
    {
        $this->dorsal = $dorsal;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    
    /** @PreUpdate */
    /** @PrePersist */
    public function checkBudget()
    {        
        // Aquí se gestiona la actualización del presupuesto del club.
        //
        // No lo gestiona de forma realista ni veráz el salario y provocará 
        // errores habitual.
        //
        // Sin embargo sirve para ilustrar los eventos de Doctrine y su uso
        //

        $salary      = $this->getSalary();
        $budget_rest = $this->club->getBudgetRest();
        $rest        = $budget_rest - $salary;
        
        if ( $rest < 0 )
        {            
            throw new SalaryException ( 'Invalid salary' );
        }
    }

    
    /** @PostPersist */
    public function sendCreationMessage ( )
    {
        MessengerHelper::sendWelcomeMessage ( );
    }
    
    /** @PostUpdate */
    public function sendDeleteMessage ( )
    {
        // Aquí me encuentro en una encrucijada:
        //
        // Como no borro valores, sino que desactivo, debo obtener una forma de 
        // comprobar si previamente estaba activado, porque solo se enviará el
        // mensaje si se acaba desactivar, sin embargo este evento salta siempre
        // tras actualizar la fila.
        //
        // He detectado el error y lo dejo comentado pues resolver este problema
        // no considero que sea parte fundamental del test 

        $se_acaba_de_desactivar = true;

        if ( $se_acaba_de_desactivar )
        {
            MessengerHelper::sendGoodbyeMessage();
        }
    }



    

}

app/src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Player;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('salary')
            ->add('dorsal')
            ->add('birth_date')
            ->add('active')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('club')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

app/src/Controller/API_10/PlayerController.php
<?php

namespace App\Controller\API_10;

use App\Helper\API10;
use App\Helper\PlayerHelper;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\PlayerRepository;
use App\Entity\Player;
use App\Exception\InvalidClubException;

#[Route('/API/1.0/player')]
class PlayerController extends API10
{
    public function __construct (
        private EntityManagerInterface $entityManager, 
        private ManagerRegistry        $managerRegistry,
    )
    {
        // Powered by PHP 8.1 "in initializers" new feature. It makes
        // inneccesary to create and initilize the $this->repository variable

        $this->class      = Player::class;
        $this->repository = new PlayerRepository ( $managerRegistry );
        $this->em         = $entityManager;
        $this->mr         = $managerRegistry;

        $this->serializer = function ( $collection )
        {
            $return = [ ];

            foreach ( $collection as $value )
            {
                $id = $value->getId ( );
                $return [ $id ] =
                [
                    'id'         => $id,
                    'club'       => $value->getClub()?->getName(),
                    'name'       => $value->getName(),
                    'salary'     => $value->getSalary(),
                    'dorsal'     => $value->getDorsal(),
                    'birth_date' => $value->getBirthDate(),
                    'active'     => $value->getActive(),
                    'created_at' => $value->getCreatedAt(),
                    'update_at'  => $value->getUpdatedAt(),
                ];
            }

            return $return;
        };


        $this->persistObject = function ( $object, $content )
        {
            $decoded    = json_decode ( $content );
            $id         = $decoded->club;
            $repository = new \App\Repository\ClubRepository ( $this->managerRegistry );
            $data       = $repository->findBy ( [ 'id' => $id ] ) [0] ?? false;

            if ( !$data )
            {
                throw new InvalidClubException ( 'Invalid club' );
            }

            $object->setClub      ( $data );
            $object->setName      ( $decoded->name             ?? '' );
            $object->setSalary    ( (float) ( $decoded->salary ?? 0  ) );
            $object->setDorsal    ( (int)   ( $decoded->dorsal ?? NULl )) ;
            $object->setBirthDate ( new \Datetime ( $decoded->birth_date->date ?? NULL ) );
            $object->setActive    ( $decoded->active     ?? '0' );
            
            $this->entityManager->persist (  $object );
            $this->entityManager->flush();
        };
    }    


    #[Route("/", name: "API_10_player_index", methods: ["GET"])]
    public function index ( Request $request ): JsonResponse
    {
        return parent::index ( $request );
    }
    
    
    #[Route("/", name: "API_10_player_new", methods: ["POST"])]
    public function new ( Request $request ): JsonResponse
    {
        return parent::new ( $request );
    }


    #[Route("/{id}", name: "API_10_player_show", methods: ["GET"])]
    public function show ( Request $request ): JsonResponse
    {
        return parent::show ( $request );
    }


    #[Route("/{id}", name: "API_10_player_replace", methods: ["PUT"])]
    public function replace ( Request $request ): JsonResponse
    {
        return parent::replace ( $request );
    }


    #[Route("/{id}", name: "API_10_player_delete", methods: ["DELETE"])]
    public function delete ( Request $request ): JsonResponse
    {
        return parent::delete ( $request );
    }
    

    #[Route("/{id}", name: "API_10_player_update", methods: ["PATCH"])]
    public function update ( Request $request ): JsonResponse
    {
        return parent::update ( $request );
    }


    #[Route("/club/{club_id}/{page}", name: "API_10_player_listarPorClub", methods: ["POST"])]
    public function listarPorClub ( Request $request, int $page = 1 ): JsonResponse
    {
        $club_id = $request->get ( "club_id" );
        $page    = $request->get ( "page" );
        $content = $request->getContent ( );
        $decoded = json_decode ( $content, true );
        $filter  = [ $decoded ['filter'] ] [ 0 ] ?? NULL;
        
        $itemsPerPage = 3; // sería mejor si lo guardo en un archivo de configuración pero el tiempo se me echa encima :(
        $firstRestult = ( $page - 1 ) * $itemsPerPage;

        $collection = PlayerHelper::Query_listarPorClub ( $filter, $this->entityManager, $this->class, $club_id, $itemsPerPage, $firstRestult );

        return $this->createSerializedJSONResponse ( $collection );
    }    
}

app/src/Controller/CRUD/PlayerController.php
<?php

namespace App\Controller\CRUD;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/CRUD/player')]
class PlayerController extends AbstractController
{
    #[Route('/', name: 'player_index', methods: ['GET'])]
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'player_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/new.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'player_show', methods: ['GET'])]
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    #[Route('/{id}/edit', name: 'player_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/edit.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'player_delete', methods: ['POST'])]
    public function delete(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $entityManager->remove($player);
            $entityManager->flush();
        }

        return $this->redirectToRoute('player_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/player/_delete_form.html.twig
<form method="post" action="{{ path('player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/player/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
    <h1>Edit Player</h1>

    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('player_index') }}">back to list</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}

app/templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player index{% endblock %}

{% block body %}
    <h1>Player index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Salary</th>
                <th>Dorsal</th>
                <th>Birth_date</th>
                <th>Active</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.name }}</td>
                <td>{{ player.salary }}</td>
                <td>{{ player.dorsal }}</td>
                <td>{{ player.birthDate ? player.birthDate|date('Y-m-d') : '' }}</td>
                <td>{{ player.active }}</td>
                <td>{{ player.createdAt ? player.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ player.updatedAt ? player.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('player_show', {'id': player.id}) }}">show</a>
                    <a href="{{ path('player_edit', {'id': player.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('player_new') }}">Create new</a>
{% endblock %}

app/templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a href="{{ path('player_index') }}">back to list</a>
{% endblock %}

app/templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
    <h1>Player</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ player.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ player.name }}</td>
            </tr>
            <tr>
                <th>Club</th>
                <td>{{ player.club }}</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>{{ player.salary }}</td>
            </tr>
            <tr>
                <th>Dorsal</th>
                <td>{{ player.dorsal }}</td>
            </tr>
            <tr>
                <th>Birth_date</th>
                <td>{{ player.birthDate ? player.birthDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ player.active }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ player.createdAt ? player.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ player.updatedAt ? player.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('player_index') }}">back to list</a>
    |
    <a href="{{ path('player_edit', {'id': player.id}) }}">edit</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}