app/src/Entity/Manager.php
<?php

namespace App\Entity;

use App\Entity\Traits\Active;
use App\Entity\Traits\Timestamps;
use Doctrine\ORM\Mapping as ORM;
use App\Exception\SalaryException;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PostPersist;
use Doctrine\ORM\Mapping\PostUpdate;
use Doctrine\ORM\Mapping\PrePersist;
use App\Helper\MessengerHelper;


/**
 * @ORM\Entity(repositoryClass=ManagerRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Manager
{
    use Active;
    use Timestamps;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Club::class, inversedBy="managers")
     */
    private $club;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $salary;

    /**
     * @ORM\Column(type="date")
     */
    private $license_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClub(): ?Club
    {
        return $this->club;
    }

    public function setClub(?Club $club): self
    {
        $this->club = $club;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSalary(): ?float
    {
        return $this->salary;
    }

    public function setSalary(?float $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getLicenseDate(): ?\DateTimeInterface
    {
        return $this->license_date;
    }

    public function setLicenseDate(\DateTimeInterface $license_date): self
    {
        $this->license_date = $license_date;

        return $this;
    }
    
    public function __toString()
    {
        return $this->name;
    }
    

    /** @PreUpdate */
    /** @PrePersist */
    public function checkBudget()
    {        
        // Aquí se gestiona la actualización del presupuesto del club.
        //
        // No lo gestiona de forma realista ni veráz el salario y provocará 
        // errores habitual.
        //
        // Sin embargo sirve para ilustrar los eventos de Doctrine y su uso
        //

        $salary      = $this->getSalary();
        $budget_rest = $this->club->getBudgetRest();
        $rest        = $budget_rest - $salary;
        
        if ( $rest < 0 )
        {            
            throw new SalaryException ( 'Invalid salary' );
        }
    }

    /** @PostPersist */
    public function sendCreationMessage ( )
    {
        MessengerHelper::sendWelcomeMessage ( );
    }
    
    /** @PostUpdate */
    public function sendDeleteMessage ( )
    {
        // Aquí me encuentro en una encrucijada:
        //
        // Como no borro valores, sino que desactivo, debo obtener una forma de 
        // comprobar si previamente estaba activado, porque solo se enviará el
        // mensaje si se acaba desactivar, sin embargo este evento salta siempre
        // tras actualizar la fila.
        //
        // He detectado el error y lo dejo comentado pues resolver este problema
        // no considero que sea parte fundamental del test 

        $se_acaba_de_desactivar = true;

        if ( $se_acaba_de_desactivar )
        {
            MessengerHelper::sendGoodbyeMessage();
        }
    }    
}

app/src/Form/ManagerType.php
<?php

namespace App\Form;

use App\Entity\Manager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ManagerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('salary')
            ->add('license_date')
            ->add('active')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('club')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Manager::class,
        ]);
    }
}

app/src/Controller/API_10/ManagerController.php
<?php

namespace App\Controller\API_10;

use App\Helper\API10;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\ManagerRepository;
use App\Entity\Manager;
use App\Exception\InvalidClubException;

#[Route('/API/1.0/manager')]
class ManagerController extends API10
{
    public function __construct (
        private EntityManagerInterface $entityManager, 
        private ManagerRegistry        $managerRegistry,
    )
    {
        // Powered by PHP 8.1 "in initializers" new feature. It makes
        // inneccesary to create and initilize the $this->repository variable

        $this->class      = Manager::class;
        $this->repository = new ManagerRepository ( $managerRegistry );
        $this->em         = $entityManager;
        $this->mr         = $managerRegistry;

        $this->serializer = function ( $collection )
        {
            $return = [ ];

            foreach ( $collection as $value )
            {
                $id = $value->getId ( );
                $return [ $id ] =
                [
                    'id'           => $id,
                    'club'         => $value->getClub()?->getName(),
                    'name'         => $value->getName(),
                    'salary'       => $value->getSalary(),
                    'license_date' => $value->getLicenseDate(),
                    'active'       => $value->getActive(),
                    'created_at'   => $value->getCreatedAt(),
                    'update_at'    => $value->getUpdatedAt(),
                ];
            }

            return $return;
        };


        $this->persistObject = function ( $object, $content )
        {
            $decoded    = json_decode ( $content );
            $id         = $decoded->club;
            $repository = new \App\Repository\ClubRepository ( $this->managerRegistry );
            $data       = $repository->findBy ( [ 'id' => $id ] ) [0] ?? false;

            if ( !$data )
            {
                throw new InvalidClubException ( 'Invalid club' );
            }

            $object->setClub        ( $data );
            $object->setName        ( $decoded->name             ?? '' );
            $object->setSalary      ( (float) ( $decoded->salary ?? 0  ) );
            $object->setLicenseDate ( new \Datetime ( $decoded->license_date->date ?? NULL ) );
            $object->setActive      ( $decoded->active     ?? '0' );
            
            $this->entityManager->persist (  $object );
            $this->entityManager->flush();
        };
    }    


    #[Route("/", name: "API_10_manager_index", methods: ["GET"])]
    public function index ( Request $request ): JsonResponse
    {
        return parent::index ( $request );
    }
    
    
    #[Route("/", name: "API_10_manager_new", methods: ["POST"])]
    public function new ( Request $request ): JsonResponse
    {
        return parent::new ( $request );
    }


    #[Route("/{id}", name: "API_10_manager_show", methods: ["GET"])]
    public function show ( Request $request ): JsonResponse
    {
        return parent::show ( $request );
    }


    #[Route("/{id}", name: "API_10_manager_replace", methods: ["PUT"])]
    public function replace ( Request $request ): JsonResponse
    {
        return parent::replace ( $request );
    }


    #[Route("/{id}", name: "API_10_manager_delete", methods: ["DELETE"])]
    public function delete ( Request $request ): JsonResponse
    {
        return parent::delete ( $request );
    }
    

    #[Route("/{id}", name: "API_10_manager_update", methods: ["PATCH"])]
    public function update ( Request $request ): JsonResponse
    {
        return parent::update ( $request );
    }
}

app/src/Controller/CRUD/ManagerController.php
<?php

namespace App\Controller\CRUD;

use App\Entity\Manager;
use App\Form\ManagerType;
use App\Repository\ManagerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/CRUD/manager')]
class ManagerController extends AbstractController
{
    #[Route('/', name: 'manager_index', methods: ['GET'])]
    public function index(ManagerRepository $managerRepository): Response
    {
        return $this->render('manager/index.html.twig', [
            'managers' => $managerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'manager_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $manager = new Manager();
        $form = $this->createForm(ManagerType::class, $manager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($manager);
            $entityManager->flush();

            return $this->redirectToRoute('manager_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('manager/new.html.twig', [
            'manager' => $manager,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'manager_show', methods: ['GET'])]
    public function show(Manager $manager): Response
    {
        return $this->render('manager/show.html.twig', [
            'manager' => $manager,
        ]);
    }

    #[Route('/{id}/edit', name: 'manager_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Manager $manager, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ManagerType::class, $manager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('manager_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('manager/edit.html.twig', [
            'manager' => $manager,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'manager_delete', methods: ['POST'])]
    public function delete(Request $request, Manager $manager, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$manager->getId(), $request->request->get('_token'))) {
            $entityManager->remove($manager);
            $entityManager->flush();
        }

        return $this->redirectToRoute('manager_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/manager/_delete_form.html.twig
<form method="post" action="{{ path('manager_delete', {'id': manager.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ manager.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/manager/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/manager/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Manager{% endblock %}

{% block body %}
    <h1>Edit Manager</h1>

    {{ include('manager/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('manager_index') }}">back to list</a>

    {{ include('manager/_delete_form.html.twig') }}
{% endblock %}

app/templates/manager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Manager index{% endblock %}

{% block body %}
    <h1>Manager index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Salary</th>
                <th>License_date</th>
                <th>Active</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for manager in managers %}
            <tr>
                <td>{{ manager.id }}</td>
                <td>{{ manager.name }}</td>
                <td>{{ manager.salary }}</td>
                <td>{{ manager.licenseDate ? manager.licenseDate|date('Y-m-d') : '' }}</td>
                <td>{{ manager.active }}</td>
                <td>{{ manager.createdAt ? manager.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ manager.updatedAt ? manager.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('manager_show', {'id': manager.id}) }}">show</a>
                    <a href="{{ path('manager_edit', {'id': manager.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('manager_new') }}">Create new</a>
{% endblock %}

app/templates/manager/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Manager{% endblock %}

{% block body %}
    <h1>Create new Manager</h1>

    {{ include('manager/_form.html.twig') }}

    <a href="{{ path('manager_index') }}">back to list</a>
{% endblock %}

app/templates/manager/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Manager{% endblock %}

{% block body %}
    <h1>Manager</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ manager.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ manager.name }}</td>
            </tr>
            <tr>
                <th>Club</th>
                <td>{{ manager.club }}</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>{{ manager.salary }}</td>
            </tr>
            <tr>
                <th>License_date</th>
                <td>{{ manager.licenseDate ? manager.licenseDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ manager.active }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ manager.createdAt ? manager.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ manager.updatedAt ? manager.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('manager_index') }}">back to list</a>
    |
    <a href="{{ path('manager_edit', {'id': manager.id}) }}">edit</a>

    {{ include('manager/_delete_form.html.twig') }}
{% endblock %}